potato-fixers/quiz-whiz

.github/workflows/deploy.yml
Test running CD config vi Github Actions on merge to specified branch (will change to 'main' when confirmed working)
=> Test CD Pipeline

.github/workflows/deploy.yml
Updated/fixed uses syntax error for checkout step
=> Re-attempt

.github/workflows/deploy.yml
Attempt env config for debugging AWS Region Syntax Error
=> Re-attempt cd workflow

.github/workflows/deploy.yml
…ng. Replaced aws-region key / moved it to the top of the aws steps section
=> Replaced aws-region key / Updated to Node16 from 12

.github/workflows/deploy.yml
Updated aws config syntax again  + removed Node logic
=> Linter passed with no errors

.github/workflows/deploy.yml
Refactored `deploy.yml` to remove AWS CodeDeploy in favor of SSH-ing directly into the instance
=> Test deploy to EC2 

client/src/components/take-quiz/quiz-components/Begin.jsx
Checking updated CD config one more time before merging to main.
=> Re-Run CD Pipeline with Visual Confirmation (Changed Begin Quiz Text)

server/database/index.js, server/index.js, server/middlewares/index.js
Route utilizes a post request to /create which then receives quiz form data. Quiz form data is then placed into database method to put information into db. Route is not fully defined just basic code in place to be further exapnded on with actual query string and data.
=> Set up basic route / db method for Create Quiz Feature.

client/src/App.jsx, client/src/App.test.js, client/src/Nav.jsx
Created a Nav component and imported it to App.jsx.
Nav component implementation can be found in Nav.jsx.
=> Created a navigation bar using MUI

client/src/App.jsx, client/src/Nav.jsx
Added some logic to the useEffect hook in the Nav bar component. Now, if a user refreshes the page while in the middle of taking a Quiz, they won't be redirected to the Home Screen
=> Patched Nav Bar Redirects to Home Screen on Page Refresh

server/database/schema.sql, server/database/scripts/createFavorites.js
Created a table script for favorite quizzes.
=> created table script for favorites

Dockerfile, client/src/components/take-quiz/quiz-components/Review.jsx, client/src/components/take-quiz/quiz-components/Summary.jsx, client/src/components/take-quiz/quiz-components/Timer.jsx, server/index.js
Implemented the Take Quiz timer, it now renders and counts down on the Question Screen
=> Take Quiz Timer - Stacked on PR #41

.github/workflows/deploy.yml
=> Cd Test v2

client/package-lock.json, client/src/App.jsx, client/src/Nav.jsx, client/src/components/create-quiz/CreateQuiz.jsx, client/src/components/create-quiz/quiz-components/API-Questions.jsx, client/src/components/create-quiz/quiz-components/Categories.jsx, client/src/components/create-quiz/quiz-components/MC-Questions.jsx, client/src/components/create-quiz/quiz-components/TF-Questions.jsx, client/src/components/create-quiz/styles/create-quiz.css, package-lock.json, server/package-lock.json
=> Create quiz frontend

client/src/components/user-dashboard/Dashboard.jsx, client/src/components/user-dashboard/components/Favorites.jsx, client/src/components/user-dashboard/components/History.jsx, client/src/components/user-dashboard/components/MyQuizzes.jsx, client/src/components/user-dashboard/components/TabsBar.jsx, client/src/components/user-dashboard/components/subComponents/FilterBar.jsx
Found the issue caused by using JoyUI and MaterialUI together in the FilterBar component
Re-implemented FilterBar using only MaterialUI
Changed Plays to History
Rearranged FilterBar component.
Added heart icon to the history list item for add-to-favorites feature.
=> FilterBar bug

client/src/components/global/UserContext.jsx, client/src/components/user-auth/Login-Form.jsx, client/src/index.js
Notes:
- Implemented UserContext 
- Only states so far is : isLogged
**To use:**
import React, { useContext } from 'react';
import { UserContext } from '../global/UserContext';
const { user } = useContext(UserContext);
**To Edit what you need**
edit it in components/global/userProvider
=> User auth react states

server/database/config/index.js, server/database/index.js, server/database/scripts/take-quiz/utilities.js, server/index.js, server/package-lock.json
const db = require(config/index) for all db connections
=> refactored to use only one pool config connection

client/example.env, server/index.js, server/package-lock.json, server/package.json
Changes
- npm i cors and added cors header
- added example.env file as template for client/env for api usage
Notes:
- CRA requires that all variables name be prefix with REACT_APP_VARIABLE NAME
=> Connecting client to API

client/src/components/create-quiz/CreateQuiz.jsx, client/src/components/create-quiz/quiz-components/Categories.jsx, client/src/components/create-quiz/quiz-components/MC-Questions.jsx, server/controllers/create/quizzes.js, server/controllers/index.js, server/database/config/index.js, server/database/index.js, server/database/models/create/create-quiz.js, server/database/scripts/createQuiz.js, server/index.js, server/package-lock.json, server/package.json, server/routes/create-quiz.js, server/routes/index.js
Backend working properly. Data send from client is being received and inputted into Postgres Database.
Tested for MC / TF Quizzes, Only TF Quizzes, and Only MC Quizzes.
Added body-parser for incoming requests. All routes/models using proper exports and matching file structure.
=> Create Quiz Backend

server/index.js, server/package-lock.json
=> Cors hotfix.

server/database/index.js, server/index.js
Changes
- cors was required twice in server/index
- incorrect require statement database/index
=> merge conflict hot fixes

.github/workflows/deploy.yml
=> Test Patch CD

client/package-lock.json, client/src/components/user-dashboard/Dashboard.jsx, client/src/components/user-dashboard/components/Favorites.jsx, client/src/components/user-dashboard/components/History.jsx, client/src/components/user-dashboard/components/MyQuizzes.jsx, client/src/components/user-dashboard/components/Overview.jsx, client/src/components/user-dashboard/components/QuizCounts.jsx, client/src/components/user-dashboard/hooks/useQuizzes.jsx, package-lock.json, package.json, server/controllers/dashboard/counts.js, server/controllers/index.js, server/database/models/dashboard/counts.js, server/database/models/dashboard/favorites.js, server/database/models/dashboard/history.js, server/database/models/dashboard/myQuizzes.js, server/database/models/dashboard/overview.js, server/database/models/index.js, server/package-lock.json, server/routes/dashboard.js
Changes:
- Made new routes to serve the counts of quizzes.
- Implemented getCounts to get the counting of quizzes from the back end.
- Refactored user dashboard front end to make API requests for data from the backend.
- Implemented a custom hook to handle fetching data for all tabs.
=> Dashboard GET requests for fetching quizzes

.github/workflows/deploy.yml
updated script so that the old container is stopped/removed, then the old image, before pulling latest from DHub and spinning up a new container
=> SSH Auth now working

client/package.json, server/Dockerfile
Build step took down the instance / reverting
=> Revert client start script to previous state (just run start, no build)

client/src/components/create-quiz/CreateQuiz.jsx
WARNING: Edited `createQuiz.jsx`, just to test client `.env` SERVER URI works. Revert and or alert Tiger for approval/changes before merging to prod
=> Test Client Env

client/src/components/user-dashboard/Dashboard.jsx, client/src/components/user-dashboard/components/DashTop.jsx
Changes:
- Added the ability to navigate to the user settings page from the dashboard.
- Utilized UserContext to show username (guest)
- Added some styling to the DashTop component.
Note: Will implement the profile image feature when the user image is finished.
=> DashTop update

client/package-lock.json, client/src/components/create-quiz/CreateQuiz.jsx, server/database/schema.sql, server/package-lock.json
In order to create quizzes, we need to be logged in.
We should create an admin account to create sample quizzes. All sample quizzes will be referenced from that id. Should drop table for users and have it as user id = 1 if possible for ease of development.
Schema has been updated from user_id TEXT to user_id INT, foreign key added to reference users(id).
=> Update Create Quiz to use profile.id instead of username.

client/src/components/home-landing/components/QuizList.jsx, client/src/components/home-landing/components/QuizListEntry.jsx
=> Update Table font size

client/src/components/create-quiz/CreateQuiz.jsx, client/src/components/create-quiz/quiz-components/MC-Questions.jsx, client/src/components/create-quiz/quiz-components/TF-Questions.jsx
=> final update
